apiVersion: v1
kind: Pod
metadata:
  name: demopod-volume
spec:
  containers:
  - image: nginx
    name: test-nginx
    volumeMounts: 
    - mountPath: /data
      name: first-volume
  volumes:
  - name: first-volume
    hostPath:
      Path: /home/optit/mydata
      type: Directory
