apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: nginx

spec:
  selector: 
    matchLabels:
      app: myapp
  replicas: 4
  template:
    metadata: 
      name: myapp-prod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:      
      - name: nginx-container
        image: nginx
