apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end


spec:
  selector: 
    matchLabels:
      app: myapp
  replicas: 4
  template:
    metadata: 
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:      
      - name: nginx-container
        image: nginx


# kubectl create -f replica.yaml

# kubectl get replicaset

# kubectl delete replicaset myapp-replicaset

# kubectl edit replicasets.apps myapp-replicaset

# kubectl delete replicationcontrollers myapp-rc

# kubectl scale replicaset myapp-replicaset --replicas=2

# kubectl scale --replicas=8 -f replica.yaml
# kubectl replace -f replica.yaml
